#!/usr/bin/env python
import time
try:
    import RPi.GPIO as GPIO
except RuntimeError:
    print("errror1")

GPIO.setmode(GPIO.BOARD)
GPIO.setup(12, GPIO.OUT)
fan = GPIO.PWM(12,100)
fan.start(50)
while True:
    tmpFile = open( '/sys/class/thermal/thermal_zone0/temp' )
    cpu_temp_raw = tmpFile.read()
    tmpFile.close()
    cpu_temp = round(float(cpu_temp_raw)/1000, 1)
    #print (cpu_temp)
    if cpu_temp >= 42.0 :
        fan.ChangeDutyCycle(0)
    if cpu_temp <= 40.0 :
        fan.ChangeDutyCycle(60)     
    time.sleep(10)


